# Generated by Django 6.0.2 on 2026-02-06 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 6, 2, 28, 2, 699743, tzinfo=datetime.timezone.utc)),
        ),
    ]
